### ISSUE TITLE
Move wasi impl to separate crate

### ISSUE THREAD

**Issue by cpuguy83** [deislabs/runwasi#16]
The repo has a few binaries and a wasi implementation that is fairly tied to wasmtime.
#15 makes the core library runtime agnostic, meaning it does not depend on wasmtime.

In order to completely remove wasmtime as a dependency from the core library it may be useful to move the binaries along with the `Wasi` instance implementation into a separate crate (of course both crates can be in this repo).

**Comment by Mossaka** [comment]
I will take this one
